image: Visual Studio 2017
version: 1.0.{build}
configuration: Release
force_https_clone: true

#cache:
#  '%USERPROFILE%\.nuget\packages'

before_build:
  - dotnet restore mns-netcore.sln
  
build:
  project: mns-netcore.sln
  verbosity: minimal
  publish_nuget: true
  
after_build:
  - dotnet pack -c Release -o .\ src\mns-netcore\mns-netcore.csproj
  
deploy:
  provider: NuGet
  api_key:
    secure: 8PX8dfRC9J5mCxCwnFB4Nb8kcP+8cVibEiR5rTYnEoa+9oALiI0gML69ugi/AByK
  skip_symbols: false
  artifact: src\mns-netcore\mns-netcore.1.0.0.nupkg
