image: Visual Studio 2017
version: 1.0.{build}
configuration: Release
force_https_clone: true

#cache:
#  '%USERPROFILE%\.nuget\packages'

before_build:
  - dotnet restore mns-netcore.sln
  
build:
  project: mns-netcore.sln
  verbosity: minimal
  publish_nuget: true
  
after_build:
  - dotnet pack -c Release -o .\ src\mns-netcore\mns-netcore.csproj
  
artifacts:
  - path: 'src\mns-netcore\mns-netcore*.nupkg'
    name: mns-netcore

deploy_script:
  - ps: >-
      echo $artifacts
