image: Visual Studio 2017
version: 0.1.{build}-alpha
configuration: Release
force_https_clone: true

#cache:
#  '%USERPROFILE%\.nuget\packages'

before_build:
  - dotnet restore mns-netcore.sln
  
build:
  project: mns-netcore.sln
  verbosity: minimal
  publish_nuget: true
  
after_build:
  - dotnet pack /p:Version=%APPVEYOR_BUILD_VERSION% -c %CONFIGURATION% -o .\ src\mns-netcore\mns-netcore.csproj
  
artifacts:
  - path: 'src\mns-netcore\mns-netcore*.nupkg'
    name: mns-netcore
  
deploy:
  provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
  api_key:
    secure: 8PX8dfRC9J5mCxCwnFB4Nb8kcP+8cVibEiR5rTYnEoa+9oALiI0gML69ugi/AByK
